model_settings:
  model_name: model-name
  save_path: /path/to/model_dir/
  save_period: 25
  seed: 101

data:
  # data_path: /path/to/datasets/CHEMS_L3_SST_Adriatic.nc
  # cloud_coverage_threshold: 0.6
  # data_path: /path/to/datasets/SST_L3_CMEMS_2006-2021_Mediterranean.nc
  # cloud_coverage_threshold: 1.0
  data_path: /path/to/datasets/CHEMS_SST_Atlantic.nc
  cloud_coverage_threshold: 0.75
  n_samples: null
  time_win: 3
  batch_size: 8
  standardize: true
  mask_in_cond: true # Mask for central day
  use_onehot: true  # Fill in context frames, offset masks are one-hot encoded
  max_delta: 3

direct_params:
  in_channels: 1
  out_channels: 1
  model_channels: 128
  channel_mult: [1, 2, 3, 4]
  num_res_blocks: 3
  num_extra_blocks: 2
  num_input_enc_blocks: 0
  num_mask_enc_blocks: 0
  attention_resolutions: [8]
  num_heads: 4
  num_head_channels: -1
  num_heads_upsample: -1
  use_new_attention_order: true
  use_scale_shift_norm: true
  resblock_updown: true
  dropout: 0.3

training:
  learning_rate: 1e-4
  optimizer_betas: [0.9, 0.95]
  decay_lr: true
  epochs: 200
